// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKiN8QFxintnbu-HWSrRaeCUbxty5Rj0g',
    appId: '1:427396067944:web:cd2e9a6469246fa27f41dd',
    messagingSenderId: '427396067944',
    projectId: 'prueba1-6e1a5',
    authDomain: 'prueba1-6e1a5.firebaseapp.com',
    databaseURL: 'https://prueba1-6e1a5-default-rtdb.firebaseio.com',
    storageBucket: 'prueba1-6e1a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTEnW_ydz40UOv8njzddWMH8Sf1aqjDuo',
    appId: '1:427396067944:android:cf397995a71452ab7f41dd',
    messagingSenderId: '427396067944',
    projectId: 'prueba1-6e1a5',
    databaseURL: 'https://prueba1-6e1a5-default-rtdb.firebaseio.com',
    storageBucket: 'prueba1-6e1a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHiq-baVcShjrJAyETsRQ4-5vIHBiUPg0',
    appId: '1:427396067944:ios:26c25707009ad6827f41dd',
    messagingSenderId: '427396067944',
    projectId: 'prueba1-6e1a5',
    databaseURL: 'https://prueba1-6e1a5-default-rtdb.firebaseio.com',
    storageBucket: 'prueba1-6e1a5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHiq-baVcShjrJAyETsRQ4-5vIHBiUPg0',
    appId: '1:427396067944:ios:26c25707009ad6827f41dd',
    messagingSenderId: '427396067944',
    projectId: 'prueba1-6e1a5',
    databaseURL: 'https://prueba1-6e1a5-default-rtdb.firebaseio.com',
    storageBucket: 'prueba1-6e1a5.firebasestorage.app',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKiN8QFxintnbu-HWSrRaeCUbxty5Rj0g',
    appId: '1:427396067944:web:496abdde4effbcf67f41dd',
    messagingSenderId: '427396067944',
    projectId: 'prueba1-6e1a5',
    authDomain: 'prueba1-6e1a5.firebaseapp.com',
    databaseURL: 'https://prueba1-6e1a5-default-rtdb.firebaseio.com',
    storageBucket: 'prueba1-6e1a5.firebasestorage.app',
  );
}
